version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data                            # Persist Redis data
      - ./redis.conf:/usr/local/etc/redis/redis.conf  # Mount custom config
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: always
